[package]
name = "doubletime"
version = "0.1.0"
edition = "2021"
author = ["Matthew R. Carbone"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["derive"] }
yaml-rust = { version = "0.4" }
